# Site settings
title: VCI
email: contact@vcichicago.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vcichicago.com" # the base hostname & protocol for your site
phone: 773-555-5555
address: "3756 W 80th, Chicago 60652"
address_url: "https://www.google.com/maps?f=q&source=s_q&q=3756+W.+80th+St+Chicago+IL+60652"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
